package math.operation.test;

import org.junit.Assert;
import org.junit.Test;

import math.operation.ArithmeticOperation;

/**
 * Test Arithmetic operations Code coverage report will be generated by Jaccod
 * Library
 * 
 * @author Anant Goswami
 *
 */
public class ArithmeticOperationTest {

	ArithmeticOperation operation = ArithmeticOperation.getInstance();

	@Test
	public void testAdd() {

		int sum = operation.add(5, 5);
		Assert.assertEquals(10, sum);
	}

	@Test
	public void testSub() {

		int sum = operation.sub(-5, 5);
		Assert.assertEquals(-10, sum);
	}

	@Test
	public void testMultiply() {

		int sum = operation.multiply(5, 5);
		Assert.assertEquals(25, sum);
	}

	@Test
	public void testDivide() {

		int sum = operation.divide(5, 5);
		Assert.assertEquals(1, sum);
	}
}
